baseURL: "https://cfe.dev/"
languageCode: "en-us"
title: "CFE.dev"
params:
  description: >-
    CFE.dev offers a large library of recorded sessions on a wide range of development
    & technology topics live as well as interactive virtual meetups featuring the experts.
  mastodon: https://techhub.social/@cfedev
  twitter: cfe_dev
  instagram: cfe_dev
  youtube: https://www.youtube.com/@cfedev
  discord: https://discord.com/invite/E2ysUYPzJH
  sponsorship: /docs/prospectus.pdf
  algolia:
    vars:
      - title
      - summary
      - date
      - permalink
      - description
    params:
      - categories
  featuredTags:
    - jamstack
    - aws
    - nextjs
    - serverless
    - devrel
    - devops
    - machine-learning
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: categories
      weight: 100
    - name: tags
      weight: 100
    - name: date
      weight: 10
paginate: 6
rssLimit: 20

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
    - HTML
    - RSS
    - Algolia
  page:
    - HTML
    - Calendar
mediaTypes:
  text/calendar:
    suffixes:
      - ics
outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true
  RSS:
    mediatype: "application/rss"
    baseName: "rss"
  Calendar:
    mediatype: "text/calendar"
    baseName: "calendar"
    isPlainText: true
